// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8nAdmTOTCl9jxioGUiTZFwzO51Id3H_8',
    appId: '1:703581243867:web:e2c9588d7650aea8b17ffe',
    messagingSenderId: '703581243867',
    projectId: 'ecom-defe6',
    authDomain: 'ecom-defe6.firebaseapp.com',
    storageBucket: 'ecom-defe6.appspot.com',
    measurementId: 'G-KP4QLN2WFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtPmS3tHKg_Zlr12cnTBhpyZMoMPZBqEs',
    appId: '1:703581243867:android:cb2aa2847c53009db17ffe',
    messagingSenderId: '703581243867',
    projectId: 'ecom-defe6',
    storageBucket: 'ecom-defe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC__B_Ts3C6p7jMgD0rwqfvtO6SePG6oyU',
    appId: '1:703581243867:ios:2c6e2b6420ce85f9b17ffe',
    messagingSenderId: '703581243867',
    projectId: 'ecom-defe6',
    storageBucket: 'ecom-defe6.appspot.com',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC__B_Ts3C6p7jMgD0rwqfvtO6SePG6oyU',
    appId: '1:703581243867:ios:906a3c1cd742399fb17ffe',
    messagingSenderId: '703581243867',
    projectId: 'ecom-defe6',
    storageBucket: 'ecom-defe6.appspot.com',
    iosBundleId: 'com.example.ecom.RunnerTests',
  );
}
